config/routes.rb
Rails.application.routes.draw do
  # Devise routes
  devise_for :users

  # User routes
  resources :users, only: [:new, :index, :show, :edit, :update] do
    resources :ticket_types, except: [:show, :index]
    resources :event_registrations, only: [ :index], as: 'my_registrations'
  end

  # Check-in routes
  resources :check_ins, only: [:index, :create]
  resources :tickets, only: [:show]

  # Other EventRegistrations
  resources :tickets, only: [:index, :show, :new, :create] do
    resources :event_registrations, only: [:new, :create, :index, :show] do
      resources :payments, only: [:new, :create, :show]
    end
  end
  #

  resources :dashboard, only: [:index]
  resources :home, only: [:index]

  resources :events do
    member do
      get 'edit_status'
      patch 'update_status'
    end
    resources :ticket_types, only: [:index, :new, :create]
    resources :event_registrations, only: [:index, :new, :create, :show, :edit, :update] do
      resources :tickets, only: [:index, :new, :create, :show, :destroy]
    end
    member do
      patch :save_draft
    end
    collection do
      post "next_step"
    end
    resources :check_ins
  end

  get "booked_for" => "event_registrations#booked_for", as: :booked_for

  # Other routes
  get "/health_check" => "rails/health#show", as: :rails_health_check

  # Root path
  root "home#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/category.rb
# app/models/category.rb
class Category < ApplicationRecord
  has_many :subcategories, dependent: :destroy
  has_many :events
  validates :name, presence: true, uniqueness: true
end

app/models/check_in.rb
class CheckIn < ApplicationRecord
  belongs_to :ticket
  belongs_to :event
  belongs_to :checked_by, polymorphic: true
end

app/models/event.rb
class Event < ApplicationRecord
  include AASM
  after_initialize :set_defaults
  belongs_to :organizer, class_name: 'User'
  has_many :ticket_types, dependent: :destroy, autosave: true
  accepts_nested_attributes_for :ticket_types
  # has_many :tickets, through: :ticket_types
  has_many :tickets, through: :event_registrations
  has_many :event_registrations
  has_many :attendees, through: :event_registrations
  has_one_attached :cover_image
  has_many_attached :gallery_images
  belongs_to :category, optional: true
  belongs_to :subcategory, optional: true
  # validates :title, :start_date, :end_date, :location, presence: true
  # validate :end_date_after_start_date

  scope :featured_events, -> { where(featured: true, status: Event.statuses[:published]) }

  scope :upcoming, -> { where('start_date >= ? AND status = ?', Date.current, Event.statuses[:published]).order(start_date: :asc) }

  #ToDo define logic for trending events, e.g weighted on tickets sold, followed, views
  scope :trending, -> { self.upcoming.order(clicks: :desc) }

  #ToDo define logic for most popular events, e.g tickets sold
  scope :most_popular, -> { self.upcoming.order(clicks: :desc).limit(10) }

  #ToDo define logic for 'more' events, e.g upcoming events
  scope :more_events, -> { where('start_date >= ? AND status = ?', Date.current, Event.statuses[:published]).order(start_date: :asc) }

  enum status: {
    draft: 1,
    published: 2,
    cancelled: 3,
    completed: 4
  }

  aasm column: :status do
    state :draft, initial: true
    state :published
    state :cancelled
    state :completed
    event :publish do
      transitions from: :draft, to: :published
      after do
        EventPublishedJob.perform_later(self)
      end
    end
    event :cancel do
      transitions from: [:draft, :published], to: :cancelled
      after do
        process_cancellation
      end
    end
  end

  def process_cancellation
    # TicketRefundJob.perform_later(self)
    # EventCancellationNotifierJob.perform_later(self)
  end

  private

  def end_date_after_start_date
    return if end_date.blank? || start_date.blank?
    errors.add(:end_date, "must be after the start date") if end_date < start_date
  end

  def set_defaults
    self.start_date ||= Date.today
    self.end_date ||= Date.today
    self.ticket_types << TicketType.default(self) if self.ticket_types.empty?
    # self.status ||= :draft
    self.current_step ||= 1
  end
end

app/models/event_registration.rb
class EventRegistration < ApplicationRecord
  belongs_to :user
  belongs_to :event
  has_one :ticket, autosave: true

  has_one_attached :ticket_pdf

  enum status: { registered: 0, attending: 1, cancelled: 2, attended: 3 }

end

app/models/follower.rb
class Follower < ApplicationRecord
  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"
end

app/models/organizer.rb
# app/models/organizer.rb
class Organizer < ApplicationRecord
  has_many :events
  has_one_attached :avatar

  has_many :followers

  def followers_count
    followers.count
  end
end

app/models/payment.rb
class Payment < ApplicationRecord
  belongs_to :event_registration
end

app/models/registration.rb
class Registration < ApplicationRecord
  belongs_to :user
  belongs_to :event

  enum status: { registered: 0, attending: 1, cancelled: 2 }
end

app/models/subcategory.rb
class Subcategory < ApplicationRecord
  belongs_to :category
  has_many :events
  validates :name, presence: true, uniqueness: { scope: :category_id }
end

app/models/ticket.rb
class Ticket < ApplicationRecord
  belongs_to :ticket_type
  belongs_to :event_registration
end

app/models/ticket_type.rb
class TicketType < ApplicationRecord
  belongs_to :event
  has_many :tickets, dependent: :destroy
  monetize :price, as: "price_cents"
  validates :name, :price, :capacity, presence: true
  # validate :capacity_within_venue_limit

  def available?
    tickets.count < capacity
  end

  def current_price
    # Dynamic pricing logic based on time/availability
    return price if tickets.count < (capacity * 0.5)
    price * 1.2 # 20% increase after 50% sold
  end

  def self.default(event)
    where(name: 'DEFAULT').first_or_create(event_id: event, name: 'DEFAULT', price: 0, capacity: 100)
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  validates :name, presence: true, length: { maximum: 20 }
  validates :email, presence: true,
            uniqueness: true,
            format: { with: /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i,
                      message: "must be a valid email address" }
  has_many :event_registrations

  has_many :active_relationships, class_name: "Follower",
           foreign_key: "follower_id",
           dependent: :destroy
  has_many :following, through: :active_relationships, source: :followed

  has_many :passive_relationships, class_name: "Follower",
           foreign_key: "followed_id",
           dependent: :destroy
  has_many :followers, through: :passive_relationships, source: :follower

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @hero = Event.featured_events.first || Event.upcoming.first
    @categories = Category.all
    @events = Event.upcoming.limit(8)
    @trending_events = Event.trending.limit(10)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def device_type
    browser = Browser.new(request.user_agent)
    if browser.device.mobile?
      :mobile
    elsif browser.device.tablet?
      :tablet
    else
      :desktop
    end
  end
end

app/helpers/check_ins_helper.rb
module CheckInsHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/payments_helper.rb
module PaymentsHelper
end

app/helpers/tickets_helper.rb
module TicketsHelper
end

app/helpers/time_helper.rb
# app/helpers/time_helper.rb
module TimeHelper
  def next_quarter_hour(time)
    minutes = (time.min / 15 + 1) * 15
    if minutes == 60
      time + (60 - time.min) * 60
    else
      time + (minutes - time.min) * 60
    end
  end

  def quater_hour_time_intervals
    intervals = []
    (0..23).each do |hour|
      ["00", "15", "30", "45"].each do |minute|
        intervals << format('%02d:%s', hour, minute)
      end
    end
    intervals
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/_article.html.erb
<% trending.each do |event| %>
<%# 30.times do |event| %>
  <div class="inline-block px-3">
    <!--    <div class="size-40 lg:size-72 overflow-hidden rounded-lg shadow-md bg-white hover:shadow-xl transition-shadow duration-300 ease-in-out">-->
    <!--      <%#= event %> event-->
    <%#= image_tag event.cover_image, class: "object-scale-down" if event.cover_image.attached? %>
    <!--    </div>-->
    <!--  </div>-->

    <% if true %>
      <article class="flex relative flex-col px-2.5 py-3 bg-white rounded-3xl border border-black border-solid min-h-[274px] w-[220px]">
        <%= image_tag event.cover_image,  class: "object-contain" if event.cover_image.attached? %>

        <div class="flex z-0 flex-col flex-1 mt-5 w-full">
          <div class="flex flex-col flex-1 w-full">
            <div class="flex gap-6 items-start w-full min-h-[30px]">
              <h3 class="flex-1 shrink text-lg font-bold leading-none text-black basis-0"><%= event.title.capitalize %></h3>
              <button>
                <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="size-6">
                  <path stroke-linecap="round" stroke-linejoin="round" d="M12 6.75a.75.75 0 1 1 0-1.5.75.75 0 0 1 0 1.5ZM12 12.75a.75.75 0 1 1 0-1.5.75.75 0 0 1 0 1.5ZM12 18.75a.75.75 0 1 1 0-1.5.75.75 0 0 1 0 1.5Z"/>
                </svg>
              </button>
            </div>
            <div class="flex flex-col flex-1 w-full text-xs font-medium leading-none text-black">
              <time datetime="2023-11-02T13:34:00"><%= event.start_date.strftime("%A, %b %d") %></time>
              <time datetime="2023-11-02T13:34:00"><%= event.start_date.strftime("%I:%M %p") %></time>
              <address><%= event.location %></address>
            </div>
          </div>
          <div class="flex gap-3.5 items-center px-1 w-full text-black">
            <div class="self-stretch my-auto text-xs font-medium leading-none"><%= event.organizer.name.capitalize %></div>
            <div class="flex-1 shrink self-stretch my-auto text-xs text-right basis-0"><%= " #{event.organizer.followers.count} followers" %></div>
          </div>
        </div>

        <div class="flex absolute right-1 top-5 z-0 flex-col pb-4 w-11 h-[43px]">
          <Button>
            <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="size-6">
              <path stroke-linecap="round" stroke-linejoin="round" d="M17.593 3.322c1.1.128 1.907 1.077 1.907 2.185V21L12 17.25 4.5 21V5.507c0-1.108.806-2.057 1.907-2.185a48.507 48.507 0 0 1 11.186 0Z"/>
            </svg>
          </button>
        </div>

      </article>
    <% end %>

  </div>
<!--  </div>-->

<% end %>

app/views/home/_carousel.html.erb
<section class="mx-auto w-[85%] flex justify-center">
  <div data-controller="carousel" class="relative h-96 overflow-hidden rounded-lg border-b-2" >

    <!-- Carousel wrapper -->
    <div class="flex items-center h-full w-full">
      <figure data-carousel-target="slide" class="duration-700 ease-in-out">
        <%= image_tag 'event-crowd-unsplash.png', class: "object-contain" %>
      </figure>

      <figure data-carousel-target="slide" class="duration-700 ease-in-out">
        <%= image_tag 'ticket_stub_series.png', class: "object-contain" %>
      </figure>

      <figure data-carousel-target="slide" class="duration-700 ease-in-out">
        <%= image_tag 'ticket_stub_start_event.png', alt: 'Ticket Stub', class: "object-contain" %>
      </figure>

    </div>

    <button data-action="carousel#prev"
            class="absolute left-0 top-1/2 transform -translate-y-1/2 bg-transparent text-slate-400 rounded-full opacity-25 hover:opacity-75">
      <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="size-8">
        <path stroke-linecap="round" stroke-linejoin="round" d="m11.25 9-3 3m0 0 3 3m-3-3h7.5M21 12a9 9 0 1 1-18 0 9 9 0 0 1 18 0Z"/>
      </svg>

    </button>
    <button data-action="carousel#next"
            class="absolute right-0 top-1/2 transform -translate-y-1/2 bg-transparent text-slate-400 rounded-full opacity-25 hover:opacity-75">
      <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="size-8">
        <path stroke-linecap="round" stroke-linejoin="round" d="m12.75 15 3-3m0 0-3-3m3 3h-7.5M21 12a9 9 0 1 1-18 0 9 9 0 0 1 18 0Z"/>
      </svg>
    </button>
  </div>
</section>

app/views/home/_categories.html.erb
<section class="py-4 bg-gray-50">
  <div class="text-pretty mx-auto px-4 w-[85%] ">
    <h3 class="text-2xl font-semibold mb-2 row-span-1 text-center mb-8">Categories</h3>
    <div class="flex flex-wrap justify-start inline-block">

      <% categories.each do |category| %>
        <div class="flex flex-row justify-center">
          <%= link_to events_path(category: category.name) do %>
            <div class="relative w-64 h-64 items-center">
              <div class="top-0 w-24 h-24 bg-white rounded-full shadow-md flex mb-2">
                <%# Add category icon here %>
              </div>
              <span class="bottom-0 text-lg font-bold text-black-500 w-20 text-wrap block text-center"><%= category.name %></span>
            </div>
          <% end %>
        </div>
      <% end %>
    </div>
  </div>
</section>

app/views/home/_event_card.html.erb
<div>
  <% if event.cover_image.attached? %>
    <%= image_tag event.cover_image, class: "object-scale-down overflow-clip rounded" %>

  <% else %>

    <div class="flex items-center justify-center bg-gray-300 rounded dark:bg-gray-700 object-scale-down">
      <svg class="text-gray-200 dark:text-gray-600" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 20 18">
        <path d="M18 0H2a2 2 0 0 0-2 2v14a2 2 0 0 0 2 2h16a2 2 0 0 0 2-2V2a2 2 0 0 0-2-2Zm-5.5 4a1.5 1.5 0 1 1 0 3 1.5 1.5 0 0 1 0-3Zm4.376 10.481A1 1 0 0 1 16 15H4a1 1 0 0 1-.895-1.447l3.5-7A1 1 0 0 1 7.468 6a.965.965 0 0 1 .9.5l2.775 4.757 1.546-1.887a1 1 0 0 1 1.618.1l2.541 4a1 1 0 0 1 .028 1.011Z"/>
      </svg>
    </div>

  <% end %>

  <div class="flex z-0 flex-col flex-1 mt-5 w-full">
    <div class="flex flex-col flex-1 w-full">
      <div class="flex gap-6 items-start w-full min-h-[30px]">
        <h3 class="flex-1 shrink text-lg font-bold leading-none text-black basis-0"><%= event.title.capitalize %></h3>
        <!-- ellipsis button -->
        <button>
          <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="size-6">
            <path stroke-linecap="round" stroke-linejoin="round" d="M12 6.75a.75.75 0 1 1 0-1.5.75.75 0 0 1 0 1.5ZM12 12.75a.75.75 0 1 1 0-1.5.75.75 0 0 1 0 1.5ZM12 18.75a.75.75 0 1 1 0-1.5.75.75 0 0 1 0 1.5Z"/>
          </svg>
        </button>
      </div>
      <div class="flex flex-col flex-1 w-full text-xs text-base/1 font-normal leading-3 text-black">
        <time datetime="2023-11-02T13:34:00"><%= event.start_date.strftime("%a, %b %d @ %I:%M %p") %></time>
        <address><%= event.location %></address>
      </div>
    </div>
    <div class="flex gap-3.5 items-center px-1 w-full text-black">
      <div class="self-stretch my-auto text-xs font-medium leading-none"><%= "By #{event.organizer.name.capitalize}"%></div>
      <div class="flex-1 shrink self-stretch my-auto text-xs text-right basis-0"><%= " #{event.organizer.followers.count} followers" %></div>
    </div>
  </div>

  <!-- favourite now button -->
  <div class="flex absolute right-1 top-5 z-0 flex-col pb-4 w-11 h-[43px]">
    <Button>
      <svg xmlns="http://www.w3.org/2000/svg" fill="fuchsia" fill-opacity="0.5"  viewBox="0 0 24 24" stroke-width="2.5" stroke="currentColor" class="size-6 fill-fuchsia-500 bg-white/50 rounded">
        <path stroke-linecap="round" stroke-linejoin="round" d="M17.593 3.322c1.1.128 1.907 1.077 1.907 2.185V21L12 17.25 4.5 21V5.507c0-1.108.806-2.057 1.907-2.185a48.507 48.507 0 0 1 11.186 0Z"/>
      </svg>
    </button>
  </div>
</div>

<%= link_to 'Details & Tickets', event_path(event),
            class: 'text-white bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:ring-blue-300 font-medium rounded-lg text-sm text-center px-5 py-2.5 me-2 mt-2 dark:bg-blue-600 dark:hover:bg-blue-700 focus:outline-none dark:focus:ring-blue-800' %>

app/views/home/_events_cards_horizontal.html.erb
<% if event_list %>
  <% event_list.each do |event| %>

    <div class="inline-block px-2">
      <article class="flex relative flex-col px-2.5 py-3 bg-white rounded-3xl border border-black border-solid min-h-[274px] w-[220px]">
        <%= render partial: "event_card", locals: { event: event } %>
      </article>
    </div>

  <% end %>
<% end %>

app/views/home/_events_cards_verticle.html.erb
<% if event_list %>
  <% event_list.each do |event| %>

    <div class="inline-block px-1 mb-2">
      <article class="flex relative flex-col px-2.5 py-3 bg-white rounded-3xl border border-black border-solid min-h-[274px]">
        <%= render partial: "event_card", locals: { event: event } %>
      </article>
    </div>

  <% end %>
<% end %>

app/views/home/_large_screen_sections.html.erb
<%# Event Listings %>

<section>
  <div class="flex flex-row mb-2 justify-center">
    <span> <h3 class="text-2xl font-semibold row-span-1 text-center">Browsing events near you</h3></span>
  </div>
  <div class="flex flex-row justify-center mb-6">
      <div class="flex flex-row justify-between space-x-12">
        <button class="px-1 py-1 text-lg font-light rounded-full hover:bg-gray-50">All</button>
        <button class="px-1 py-1 text-lg font-light rounded-full hover:bg-gray-50">For You</button>
        <button class="px-1 py-1 text-lg font-light rounded-full hover:bg-gray-50">Online</button>
        <button class="px-1 py-1 text-lg font-light rounded-full hover:bg-gray-50">Today</button>
        <button class="px-1 py-1 text-lg font-light rounded-full hover:bg-gray-50">Free</button>
        <button class="px-1 py-1 text-lg font-light rounded-full hover:bg-gray-50">Music</button>
        <button class="px-1 py-1 text-lg font-light rounded-full hover:bg-gray-50">Community</button>
        <button class="px-1 py-1 text-lg font-light rounded-full hover:bg-gray-50">Sports</button>
      </div>
  </div>
</section>

<!-- ALL Events Section -->

<section>
  <div class="flex justify-center">
    <div class="grid grid-cols-4 gap-3 justify-center">
          <%= render partial: "events_cards_horizontal", locals: { event_list: @trending_events } %>

    </div>
  </div>
</section>

<!--  All Events Section -->

<%# Interests Section %>

<section class="py-12 bg-gray-50 mx-auto shadow border-gray-200 w-[100%] flex justify-center">
  <div class="mx-auto px-4 ">
    <h3 class="text-2xl font-semibold mb-4">Let's make it personal!</h3>
    <p class="text-gray-600 mb-8">Select your interests to get event suggestions based on what you love</p>
    <div class="flex flex-wrap gap-4">
      <% interests = ['Badminton', 'Cricket', 'Music', 'Cooking', 'Travelling', 'Dancing', 'Art', 'Designing', 'Political Science', 'Party', 'Singing', 'EDM'] %>
      <% interests.each do |interest| %>
        <button class="px-4 py-2 text-sm rounded-full border border-gray-300 hover:bg-gray-50">
          <%= interest %>
        </button>
      <% end %>
    </div>
  </div>
</section>

app/views/home/_mobile_index.html.erb
<div class="flex flex-col">
  <div class="flex justify-center mt-4 mb-8">
    <%= render "shared/mobile_search" %>
  </div>

  <!-- Trending Events Section -->
  <section>
    <div class="flex justify-between lg:justify-center items-center mb-4">
      <h2 class="text-lg font-bold text-indigo-900 ml-2">Trending Events</h2>
      <%# <a href="#" class="text-sm text-gray-600">See All</a> %>
    </div>
    <!-- Events Carousel -->
    <div class="mb-8 flex justify-center">
      <div class="flex flex-col bg-white max-w-[319px]">
        <div class="flex overflow-x-auto pb-10 hide-scroll-bar">
          <div class="flex flex-nowrap">
            <%= render partial: "events_cards_horizontal", locals: { event_list: @trending_events } %>
          </div>
        </div>
      </div>
    </div>

  </section>

  <!-- Most Popular Section -->
  <section>
    <div class="flex justify-between lg:justify-center items-center mb-4">
      <h2 class="text-lg font-bold text-indigo-900 ml-2">Most Popular</h2>
      <%# <a href="#" class="text-sm text-gray-600">See All</a> %>
    </div>
    <!-- Events Carousel -->
    <div class="mb-8 flex justify-center">
      <div class="flex flex-col bg-white max-w-[319px]">
        <div class="flex overflow-x-auto pb-10 hide-scroll-bar">
          <div class="flex flex-nowrap">
            <%= render partial: "events_cards_horizontal", locals: { event_list: @more_events } %>
          </div>
        </div>
      </div>
    </div>
  </section>

  <!-- More Events Section -->
  <section>
    <div class="flex justify-between lg:justify-center items-center mb-4">
      <h2 class="text-lg font-bold text-indigo-900 ml-2">More Events</h2>
      <%# <a href="#" class="text-sm text-gray-600">See All</a> %>
    </div>
    <div class="grid grid-cols-2 shrink content-start">
      <%= render partial: "events_cards_verticle", locals: { event_list: @trending_events } %>
    </div>
  </section>
  <style>
      .hide-scroll-bar {
          -ms-overflow-style: none;
          scrollbar-width: none;
      }

      .hide-scroll-bar::-webkit-scrollbar {
          display: none;
      }
  </style>

</div>


<!-- Most Popular Section -->
<% if false %>
  <!--  <section class="mb-8">-->
  <!--    <div class="flex justify-between items-center mb-4">-->
  <!--      <h2 class="text-lg font-semibold text-indigo-900">Most Popular</h2>-->
  <%# <a href="#" class="text-sm text-gray-600">See All</a> %>
  <!--    </div>-->

  <!--     Similar grid structure as Trending Events-->
  <!--    <div class="grid grid-cols-2 gap-4">-->
  <%# @popular_events&.each do |event| %>
  <!--         Similar card structure as above-->
  <%# end %>
  <!--    </div>-->
  <!--  </section>-->
<% end %>




<%# Event Listings %>

app/views/home/_ticket_stub_event_display.html.erb
<section>
<!--  <div class="grid grid-cols-2 md:grid-cols-3 lg:grid-cols-4 gap-2 sm:gap2 pl-1">-->
  <div class="flex flex-wrap gap-2">
    <% events.each do |event| %>
      <div class="bg-white shadow-md rounded p-1">
        <div class="relative w-full h-full flex items-center justify-center">
          <%= link_to event_path(event) do %>
            <%# if event.cover_image.attached? %>
              <%#= image_tag event.cover_image,  class: "w-full h-full" %>
            <%# else %>
              <%=  image_tag 'ticket_stub_blank.png', class: "w-full h-full" %>
              <div class="absolute bottom-0  md:bottom-ß lg:bottom-10 left-[17.5%]">
                <p class="text-center font-bold sm:font-normal text-xs md:text-lg lg:text-lg transform -rotate-90 origin-left whitespace-nowrap overflow-hidden"><%= event.start_date.strftime('%d-%m-%y@%I:%M') %></p>
              </div>
              <div class="absolute top-1 lg:top-4 left-[25%] text-brown h-[95%] w-[70%] overflow-hidden">

                <div class="grid-cols-1 h-full flex flex-col justify-between">
                  <div>
                    <p class="text-black font-bold truncate ..."><%= event.title %></p>
                    <p class="text-red-800 truncate ...">At <%= event.location %></p>
                  </div>
                  <p class="text-center text-gray-600 text-xs font-bold capitalize">By <%= event.organizer.name %></p>
                </div>

              </div>
            <%# end %>

          <% end %>
        </div>
      </div>
    <% end %>
  </div>
</section>

app/views/home/index.html.erb
<%# app/views/home/index.html.erb %>

<div class="max-w-full md:px-2">
  <% if device_type != :mobile %>

    <section>
      <%# Hero Banner %>
      <%= render partial: 'shared/hero_banner', locals: { hero: @hero } %>
    </section>

    <div class="my-6">
      <%= render partial: 'carousel', locals: { hero: @hero } %>
    </div>

    <%# Categories only available on full app%>

    <%= render partial: "categories", locals: { categories: @categories } %>

    <div class="flex flex-col bg-white max-w-screen-2xl">
      <%= render partial: "large_screen_sections" %>
    </div>
  <% end %>


  <% if device_type == :mobile %>
    <%= render partial: "mobile_index", locals: { event_list: @trending_events } %>
  <% end %>

</div>