config/routes.rb
Rails.application.routes.draw do
  # Devise routes
  devise_for :users

  # User routes
  resources :users, only: [:new, :index, :show, :edit, :update] do
    resources :ticket_types, except: [:show, :index]
    resources :event_registrations, only: [ :index], as: 'my_registrations'
  end

  # Check-in routes
  resources :check_ins, only: [:index, :create]
  resources :tickets, only: [:show]

  # Other EventRegistrations
  resources :tickets, only: [:index, :show, :new, :create] do
    resources :event_registrations, only: [:new, :create, :index, :show] do
      resources :payments, only: [:new, :create, :show]
    end
  end
  #

  resources :dashboard, only: [:index]
  resources :home, only: [:index]

  resources :events do
    member do
      get 'edit_status'
      patch 'update_status'
    end
    resources :ticket_types, only: [:index, :new, :create]
    resources :event_registrations, only: [:index, :new, :create, :show, :edit, :update] do
      resources :tickets, only: [:index, :new, :create, :show, :destroy]
    end
    member do
      patch :save_draft
    end
    collection do
      post "next_step"
    end
    resources :check_ins
  end

  get "booked_for" => "event_registrations#booked_for", as: :booked_for

  # Other routes
  get "/health_check" => "rails/health#show", as: :rails_health_check

  # Root path
  root "home#index"
end

app/models/event.rb
class Event < ApplicationRecord
  include AASM
  after_initialize :set_defaults
  belongs_to :organizer, class_name: 'User'
  has_many :ticket_types, dependent: :destroy, autosave: true
  accepts_nested_attributes_for :ticket_types
  # has_many :tickets, through: :ticket_types
  has_many :tickets, through: :event_registrations
  has_many :event_registrations
  has_many :attendees, through: :event_registrations
  has_one_attached :cover_image
  has_many_attached :gallery_images
  belongs_to :category, optional: true
  belongs_to :subcategory, optional: true
  # validates :title, :start_date, :end_date, :location, presence: true
  # validate :end_date_after_start_date

  scope :featured_events, -> { where(featured: true, status: Event.statuses[:published]) }

  scope :upcoming, -> { where('start_date >= ? AND status = ?', Date.current, Event.statuses[:published]).order(start_date: :asc) }

  #ToDo define logic for trending events, e.g weighted on tickets sold, followed, views
  scope :trending, -> { self.upcoming.order(clicks: :desc) }

  #ToDo define logic for most popular events, e.g tickets sold
  scope :most_popular, -> { self.upcoming.order(clicks: :desc).limit(10) }

  #ToDo define logic for 'more' events, e.g upcoming events
  scope :more_events, -> { where('start_date >= ? AND status = ?', Date.current, Event.statuses[:published]).order(start_date: :asc) }

  enum status: {
    draft: 1,
    published: 2,
    cancelled: 3,
    completed: 4
  }

  aasm column: :status do
    state :draft, initial: true
    state :published
    state :cancelled
    state :completed
    event :publish do
      transitions from: :draft, to: :published
      after do
        EventPublishedJob.perform_later(self)
      end
    end
    event :cancel do
      transitions from: [:draft, :published], to: :cancelled
      after do
        process_cancellation
      end
    end
  end

  def process_cancellation
    # TicketRefundJob.perform_later(self)
    # EventCancellationNotifierJob.perform_later(self)
  end

  private

  def end_date_after_start_date
    return if end_date.blank? || start_date.blank?
    errors.add(:end_date, "must be after the start date") if end_date < start_date
  end

  def set_defaults
    self.start_date ||= Date.today
    self.end_date ||= Date.today
    self.ticket_types << TicketType.default(self) if self.ticket_types.empty?
    # self.status ||= :draft
    self.current_step ||= 1
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  include Pundit::Authorization
  before_action :authenticate_user!, except: [:index, :show]
  #TODO: check if all actons are needed given use of commands.
  before_action :set_event, only: [:show, :edit, :update, :destroy, :edit_status, :update_status]
  before_action :authorize_event, only: [ :edit, :update, :destroy, :edit_status, :update_status]
  before_action :authorize_new_event, only: [:new, :create]
  before_action :authorize_edit_status, only: [:edit_status, :update_status]

  helper_method :event_owner?

  def index
    @categories = Category.all
    if params[:category].present?
      @category = Category.find_by(name: params[:category])
      @events = @category.events.published.order(start_date: :asc)
    else
      @events = Event.published.order(start_date: :asc)
    end
    # @events = Event.published.order(start_date: :asc)
  end

  def show
    @ticket_types = @event.ticket_types.includes(:tickets)
    @event_registrations = @event.event_registrations.all
    @event.increment!(:clicks)
  end

  def edit_status
    render partial: 'edit_status', locals: { event: @event }
  end

  def update_status
    if @event.update(event_params)
      respond_to do |format|
        format.turbo_stream do
          render turbo_stream: turbo_stream.replace("event_status_#{@event.id}", partial: "events/status", locals: { event: @event })
        end
        format.html { redirect_to @event, notice: 'Status was successfully updated.' }
      end
    else
      render partial: 'edit_status', locals: { event: @event }, status: :unprocessable_entity
    end
  end

  def new
    @event = Event.new
  end

  def create
    puts "!!!! IN CREATE !!!!"

    command = Events::CreateEventCommand.new(params: event_params, organizer: current_user)
    if command.call
      @event = command.event
      @event.current_step = 2 # Move to next step for rendering.
      @event.save
      render turbo_stream: turbo_stream.replace("event-form-container", partial: step_partial, locals: { event: @event })
    else
      @event.current_step = 1 # Stay on the same step for rendering.
      flash.now[:alert] = "Invalid Data!"
      render turbo_stream: turbo_stream.replace("event-form-container", partial: step_partial, locals: { event: @event })
    end
  end

  def update
    puts "!!!! IN SAVE UPDATE !!!!"
    command = Events::UpdateEventCommand.call(params: event_params, organizer: current_user)
    if command.success?
      redirect_to @event, notice: 'Event was successfully updated.'
    else
      flash.now[:alert] = "Invalid Data!"
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @event.destroy
    redirect_back fallback_location: events_url, notice: 'Event was successfully destroyed.'
  end

  def save_draft
    puts "!!!! IN SAVE DRAFT !!!!"

    if params[:id].present?
      @event = Event.find(params[:id])
      @event.assign_attributes(event_params)
      @event.current_step = next_step
    else
      @event = Event.new(event_params)
    end

    if @event.save
      # render turbo_stream: turbo_stream.replace("form_step", partial: step_partial, locals: { event: @event })
      render turbo_stream: turbo_stream.replace("event-form-container", partial: step_partial, locals: { event: @event })
    else
      render turbo_stream: turbo_stream.replace("event-form-container", partial: step_partial, locals: { event: @event })
    end
  end

  private

  def set_event
    @event = Event.find_by_id(params[:id])
    redirect_to events_path, alert: 'Event not found.' unless @event
  end

  def authorize_event
    authorize @event
  end

  def authorize_new_event
    authorize Event
  end

  def authorize_edit_status
    authorize @event, :edit_status?
  end

  def event_params

    permitted_params = params.require(:event).permit(
      :event_type, :occasion, :title, :description, :start_date, :end_date,
      :location, :step, :invite_list, :budget_item,
      :venue, :cover_image, :status, gallery_images: [], ticket_types: [],
      ticket_types_attributes: [:name, :description, :price, :capacity]
    ).merge(id: params[:id])

    unless params[:event][:start_date].present?
      params.require(:event).merge(start_date: merge_start_date_params)
      permitted_params = permitted_params.merge(start_date: merge_start_date_params)
    end

    unless params[:event][:end_date].present?
      params.require(:event).merge(end_date: merge_end_date_params)
      permitted_params = permitted_params.merge(end_date: merge_end_date_params)
    end

    permitted_params.except(:event_type, :occasion, :invite_list, :budget_item, :start_date_text, :end_date_text, :start_time, :end_time,)
  end

  def merge_start_date_params
    if params[:event][:start_date_text].present? && params[:event][:start_time].present?
      start_date = Date.parse(params[:event][:start_date_text])
      start_time = Time.parse(params[:event][:start_time])
      return DateTime.new(start_date.year, start_date.month, start_date.day, start_time.hour, start_time.min)
    end
  end

  def merge_end_date_params
    if params[:event][:end_date_text].present? && params[:event][:end_time].present?
      end_date = Date.parse(params[:event][:end_date_text])
      end_time = Time.parse(params[:event][:end_time])
      return DateTime.new(end_date.year, end_date.month, end_date.day, end_time.hour, end_time.min)
    end
  end

  def event_owner?
    current_user == @event.organizer
  end

  def next_step
    @event.current_step + 1
  end

  def step_partial(step = nil)
    switcher = step || @event.current_step
    case switcher
    when 1
      "events/partials/forms/step_1_basic_data"
    when 2
      "events/partials/forms/step_2_media_data"
    when 3
      "events/partials/forms/step_3_invitee_data"
    when 4
      "events/partials/forms/step_4_contact_data"
    when 5
      "events/partials/forms/step_5_budget_data"
    when 6
      "events/partials/forms/step_6_payment_data"
    when 7
      "events/partials/forms/step_7_completed"
    else
      "events/partials/forms/step_1_basic_data"
    end
  end
end

app/views/events/_edit_status.html.erb
<%= turbo_frame_tag "event_status_#{@event.id}" do %>
  <%= form_with(model: @event, url: update_status_event_path(@event), local: false) do |f| %>
    <div>
      <%= f.label :status %>
      <%= f.select :status, Event.statuses.keys.map { |status| [status.humanize, status] } %>
    </div>
    <div>
      <%= f.submit "Update Status" %>
    </div>
  <% end %>
<% end %>

app/views/events/_form.html.erb
<%= form_with model: @event, local: true, class: "space-y-4" do |form| %>
  <%= render "shared/errors", object: @event %>
  <div>
    <%= form.label :title, "Event Title", class: "block font-semibold" %>
    <%= form.text_field :title, class: "w-full border rounded p-2" %>
  </div>

  <div>
    <%= form.label :description, "Description", class: "block font-semibold" %>
    <%= form.text_area :description, class: "w-full border rounded p-2", placeholder: "What is this event for?" %>
  </div>

  <section>
    <h2>Media Upload Section</h2>
    <div data-controller="image-preview">

      <div class="flex flex-row items-center justify-center w-full">

        <div class="grow">
          <%= form.label :cover_image,
                         class: "flex flex-col items-center justify-center w-full h-64 border-2 border-gray-300 border-dashed rounded-lg cursor-pointer bg-gray-50 dark:hover:bg-gray-800 dark:bg-gray-700 hover:bg-gray-100 dark:border-gray-600 dark:hover:border-gray-500 dark:hover:bg-gray-600" do %>


            <div class="flex flex-col items-center justify-center pt-5 pb-6" data-image-preview-target="chooser">
              <svg class="w-8 h-8 mb-4 text-gray-500 dark:text-gray-400" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 20 16">
                <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M13 13h3a3 3 0 0 0 0-6h-.025A5.56 5.56 0 0 0 16 6.5 5.5 5.5 0 0 0 5.207 5.021C5.137 5.017 5.071 5 5 5a4 4 0 0 0 0 8h2.167M10 15V6m0 0L8 8m2-2 2 2"/>
              </svg>

              <p class="mb-2 text-sm text-gray-500 dark:text-gray-400">
                <span class="font-semibold">Click to upload</span>
                or
                drag and drop</p>
              <p class="text-xs text-gray-500 dark:text-gray-400">SVG, PNG, JPG or GIF (MAX. 800x400px)</p>
            </div>
            <img data-image-preview-target="canvas" class="object-contain overflow-auto" hidden>
            <%= form.file_field :cover_image, class: "hidden", accept: "image/*", data: { image_preview_target: "source", action: "image-preview#show" } %>
          <% end %>
        </div>
      </div>
    </div>

  </section>


  <div class="flex flex-col justify-center">
    <H1>Dates</H1>

    <div id="date-range-picker" date-rangepicker  datepicker-orientation="top" datepicker-autohide datepicker-format="yyyy-mm-dd" class="flex items-center">
      <div class="relative">
        <div class="absolute inset-y-0 start-0 flex items-center ps-3 pointer-events-none">
          <svg class="w-6 h-6 text-gray-500 dark:text-gray-400" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 20 20">
            <path d="M20 4a2 2 0 0 0-2-2h-2V1a1 1 0 0 0-2 0v1h-3V1a1 1 0 0 0-2 0v1H6V1a1 1 0 0 0-2 0v1H2a2 2 0 0 0-2 2v2h20V4ZM0 18a2 2 0 0 0 2 2h16a2 2 0 0 0 2-2V8H0v10Zm5-8h10a1 1 0 0 1 0 2H5a1 1 0 0 1 0-2Z"/>
          </svg>
        </div>

        <%= form.text_field :start_date_text, id: "datepicker-range-start", value: @event.start_date.localtime.strftime("%Y-%m-%d"),
              class: "bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full ps-10 p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500",
                            placeholder: "Start Date" %>
      </div>
      <span class="mx-4 text-gray-500">to</span>
      <div class="relative" >
        <div class="absolute inset-y-0 start-0 flex items-center ps-3 pointer-events-none">
          <svg class="w-6 h-6 text-gray-500 dark:text-gray-400" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 20 20">
            <path d="M20 4a2 2 0 0 0-2-2h-2V1a1 1 0 0 0-2 0v1h-3V1a1 1 0 0 0-2 0v1H6V1a1 1 0 0 0-2 0v1H2a2 2 0 0 0-2 2v2h20V4ZM0 18a2 2 0 0 0 2 2h16a2 2 0 0 0 2-2V8H0v10Zm5-8h10a1 1 0 0 1 0 2H5a1 1 0 0 1 0-2Z"/>
          </svg>
        </div>
        <%= form.text_field :end_date_text, id: "datepicker-range-end", value: @event.end_date.localtime.strftime("%Y-%m-%d"),
                            class: "bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full ps-10 p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500",
                            placeholder: "End Date" %>
      </div>
    </div>

    <div class="flex items-center justify-stretch">
        <%#= form.label :start_time, "Start Time", class: "block mb-2 text-sm font-medium text-gray-900 dark:text-white" %>
        <div class="relative">
          <div class="absolute inset-y-0 start-0 flex items-center justify-center ps-3 pointer-events-auto">
            <svg class="w-6 h-6 text-gray-500 dark:text-gray-400" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 24 24">
              <path fill-rule="evenodd" d="M2 12C2 6.477 6.477 2 12 2s10 4.477 10 10-4.477 10-10 10S2 17.523 2 12Zm11-4a1 1 0 1 0-2 0v4a1 1 0 0 0 .293.707l3 3a1 1 0 0 0 1.414-1.414L13 11.586V8Z"/>
            </svg>
          </div>
          <%= form.time_field :start_time,
                              class: "bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full ps-12 pe-16 p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500",
                              list: "time_list", value:  @event.end_date.present? ? @event.start_date.localtime : next_quarter_hour(Time.now),
                              include_seconds: false %>
        </div>

      <span class="mx-4 text-gray-500 pl-1">to</span>
        <%#= form.label :end_time, "Event End Time", class: "block mb-2 text-sm font-medium text-gray-900 dark:text-white" %>
        <div class="relative">

          <div class="absolute inset-y-0 start-0 flex items-center ps-3 pointer-events-none">
            <svg class="w-6 h-6 text-gray-500 dark:text-gray-400" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 24 24">
              <path fill-rule="evenodd" d="M2 12C2 6.477 6.477 2 12 2s10 4.477 10 10-4.477 10-10 10S2 17.523 2 12Zm11-4a1 1 0 1 0-2 0v4a1 1 0 0 0 .293.707l3 3a1 1 0 0 0 1.414-1.414L13 11.586V8Z" clip-rule="evenodd"/>
            </svg>
          </div>

          <%= form.time_field :end_time,
                              class: "bg-gray-50 border leading-none border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full ps-12 pe-16 p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500 overflow-auto",
                              list: "time_list", value: @event.end_date.present? ? @event.start_date.localtime : next_quarter_hour(Time.now + 2.hours), include_seconds: false %>

        </div>


      <datalist id="time_list">
        <% quater_hour_time_intervals.each do |time| %>
          <option value="<%= time %>">
        <% end %>
      </datalist>

    </div>
  </div>

  <div>
    <%= form.label :location, "Event Location", class: "block font-semibold" %>
    <%= form.text_field :location, class: "w-full border rounded p-2" %>
  </div>

  <div class="flex space-x-4">
    <% if defined? button_text %>
      <%= form.submit "#{button_text}", class: "bg-blue-500 text-white px-4 py-2 rounded hover:bg-blue-700" %>
    <% else %>
      <%= form.submit class: "bg-blue-500 text-white px-4 py-2 rounded hover:bg-blue-700" %>
    <% end %>

    <%= link_to "Cancel", session[:previous_url] || root_path, class: "bg-gray-400 text-white px-4 py-2 rounded hover:bg-gray-700" %>
  </div>

<% end %>

app/views/events/_status.html.erb
<%= turbo_frame_tag "event_status_#{@event.id}" do %>
  <p>Status: <%= @event.status.humanize %></p>
  <%= link_to 'Edit Status', edit_status_event_path(@event), data: { turbo_frame: "event_status_#{@event.id}" } %>
<% end %>

app/views/events/edit.html.erb
<h2 class="text-2xl font-bold text-gray-800 mb-6">Edit Event</h2>

<%= render "form", event: @event, button_text: 'Update' %>

app/views/events/index.html.erb
<section class="mx-auto w-[97.5%]">

<h2 class="text-2xl font-bold text-gray-800 mb-6">Browse Events</h2>

<%= render partial: "events/partials/categories", locals: { categories: @categories} %>

<div class="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-6">
  <% @events.each do |event| %>
    <div class="bg-white shadow-md rounded p-4">
      <h3 class="text-xl font-semibold text-gray-800"><%= link_to event.title, event_path(event) %></h3>
      <p class="text-gray-600">Run by <%= event.organizer.name %> on <%= event.start_date %> </p>
      <p class="mt-2"><%= link_to 'View Details', event_path(event), class: "text-blue-500 hover:underline" %></p>
    </div>
  <% end %>
</div>
</section>

app/views/events/new.html.erb
<div>
  <% if device_type == :mobile %>

    <section>
      <%= render "events/partials/forms/form_header" %>
      <div id="event-form-container">
        <%= render "events/partials/forms/step_1_basic_data", event: @event %>
      </div>
    </section>
  <% else %>
    <%#= render "layouts/desktop_content" %>
    <div class="mx-auto w-[97.5%]">
      <div id="event-form-container">
      <%= render "form", event: @event, button_text: 'Create' %>
      </div>
    </div>
  <% end %>
</div>

app/views/events/show.html.erb
<div class="bg-white shadow rounded p-6 mb-6">

  <%= render partial: "events/partials/show_details", locals: { event: @event} %>

  <% if current_user == @event.organizer %>

        <%= render partial: "events/partials/event_owner_options", locals: { event: @event} %>

  <% end %>


</div>